### ISSUE TITLE
Error in order_data for Sentinel 

### ISSUE THREAD

**Issue by earthcli** [16EAGLE/getSpatialData#64] opened 2020-06-30 14:52 UTC
When I use orderrecord=order_data(records) for sentinel, I get an error as below,
Error: A column of 'records' named 'level' is required for this action, but is missing.

Currently the records is derived from the function get_records.
Since there is little information about the function order_data, I have no idea about the 'level' column, would you please tell me records should be exported from which function so that there will be a column of 'level'?

Many thanks.

**Comment by 16EAGLE** [comment] 2020-07-01 08:14
Thanks for reporting, I will look into this. Could you please tell me which product(s) you used in `get_records()`? Then I can trace why the level column was not added.

**Comment by earthcli** [comment] 2020-07-01 09:33
Thanks for your response. I am working on sentinel-1.

**Comment by 16EAGLE** [comment] 2020-07-06 13:55
This should be resolved with commit 50133dc19b97af9b339c44b027385ddd4fa2a60b. Please reinstall `getSpatialData` using `remotes::install_github("16eagle/getSpatialData")` and let me know if the problem is resolved!

**Comment by earthcli** [comment] 2020-07-07 08:28
@16EAGLE Thanks for your effort. It works. In addition, I have solved it by adding a column of level="l1" manually, by looking up all the code in the package, I found "level" is mainly works for Landset dataset.

**Closed** 2020-07-07 08:34 UTC
Labels: bug, resolved
